channels:
- conda-forge
- pyviz
- plotly
- pytorch
- ejolly
- districtdatalabs
- bokeh
- defaults
dependencies:
- bokeh
- python
- sklearn-pandas
- datalad
- tableone
- spyder
- scikit-learn
- nilearn
- nipype
- dash
- dash-bootstrap-components
- statannotations
- fastcluster
- pingouin
- mne
- tensorboardx
- neurokit2
- oct2py
- yellowbrick
- pymer4
- plotly-orca
- plotly
- pytorch
- holoviews
- hvplot
- r-essentials
- r-matrixstats
- r-repr
- r-devtools
- jupyterlab
- r-base
- r-pma
- r-dendextend
- r-circlize
- r-reticulate
- pip
- pip:
  - xmltodict
  - adjustText
  - dash-cytoscape
  - brainrender
  - network_control
  - cca-zoo
  - bctpy
  - gemmr
  - gower
  - antropy
  - pyvis
  - distro
  - abagen
  - groupyr
  - clustergrammer
  - nisupply
  - fmriprep-docker
  - lckr-jupyterlab-variableinspector
